AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  lambda-create-app

  Sample SAM Template for lambda-create-app

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 3
  Api:
    # Allows an application running locally on port 3000 to call this API
    Cors:
      AllowMethods: "'OPTIONS,POST,GET'"
      AllowHeaders: "'Content-Type'"
      AllowOrigin: "'http://localhost:3000'"

Resources:
  CreateAppFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: create-app/
      Handler: app.lambda_handler
      Runtime: python3.7
      Events:
        CreateApp:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /create-app
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  CreateAppApi:
    Description: "API Gateway endpoint URL for Prod stage for Create App function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/create-app/"
  CreateAppFunction:
    Description: "Create App Lambda Function ARN"
    Value: !GetAtt CreateAppFunction.Arn
  CreateAppFunctionIamRole:
    Description: "Implicit IAM Role created for Create App function"
    Value: !GetAtt CreateAppFunctionRole.Arn
